trigger:
- refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    VERSION_TAG=`git describe --tags`
    VERSION_TAG=${VERSION_TAG:1}
    echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
  displayName: Parse version from tag v*
  
- task: UseDotNet@2
  displayName: Install .NET
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: DotNetCoreCLI@2
  displayName: Restore NuGet
  inputs:
    command: 'restore'
    projects: |
      Cloudy.CMS/Cloudy.CMS.csproj
      Cloudy.CMS.UI/Cloudy.CMS.UI.csproj
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Build projects
  inputs:
    command: 'build'
    projects: |
      Cloudy.CMS/Cloudy.CMS.csproj
      Cloudy.CMS.UI/Cloudy.CMS.UI.csproj
    arguments: '/p:Version=$(VERSION_TAG)'

- task: DotNetCoreCLI@2
  displayName: Pack NuGet
  inputs:
    command: 'pack'
    packagesToPack: 'Cloudy.CMS/Cloudy.CMS.csproj;Cloudy.CMS.UI/Cloudy.CMS.UI.csproj'
    nobuild: true
    includesymbols: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'VERSION_TAG'

- task: NuGetCommand@2
  displayName: Push NuGet
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Cloudy.CMS nuget.org'

- script: |
    CONTAINER_NAME=`git describe --tags`
    CONTAINER_NAME=${CONTAINER_NAME:1}
    echo "step 1: $CONTAINER_NAME"
    CONTAINER_NAME=$(echo "$CONTAINER_NAME" | tr . -)
    echo "step 2: $CONTAINER_NAME"
    CONTAINER_NAME="v-$CONTAINER_NAME"
    echo "step 3: $CONTAINER_NAME"
    echo "##vso[task.setvariable variable=CONTAINER_NAME]$CONTAINER_NAME"
  displayName: Parse version from tag v*

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Bjorn Goransson Invest AB(d958417c-19ff-464e-9a51-c750674828c4)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage container create -n $(CONTAINER_NAME) --account-name cloudycmsui --public-access blob
      az storage blob upload-batch -d $(CONTAINER_NAME) --account-name cloudycmsui -s "Cloudy.CMS.UI/wwwroot" --pattern *.js
      az storage blob upload-batch -d $(CONTAINER_NAME) --account-name cloudycmsui -s "Cloudy.CMS.UI/wwwroot" --pattern *.css
      az storage blob upload-batch -d $(CONTAINER_NAME) --account-name cloudycmsui -s "Cloudy.CMS.UI/wwwroot" --pattern *.svg